# Generated by Django 3.2.23 on 2024-06-06 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'actividades',
            },
        ),
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('administrador', models.BooleanField()),
                ('img_logo', models.FileField(blank=True, null=True, upload_to='img_logo_cargos')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cargos',
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Generos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'generos',
            },
        ),
        migrations.CreateModel(
            name='Materiales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('total', models.IntegerField(default=0)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'materiales',
            },
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'niveles',
            },
        ),
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'permisos',
            },
        ),
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('numero_documento', models.BigIntegerField(unique=True)),
                ('telefono_principal', models.BigIntegerField(unique=True)),
                ('telefono_secundario', models.BigIntegerField()),
                ('correo', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'personas',
            },
        ),
        migrations.CreateModel(
            name='PrecioDolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.FloatField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'precio_dolar',
            },
        ),
        migrations.CreateModel(
            name='Recreadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inhabilitado', models.BooleanField(default=False)),
                ('img_perfil', models.FileField(blank=True, null=True, upload_to='img_recreadores')),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('genero', models.ForeignKey(db_column='genero_id', on_delete=django.db.models.deletion.PROTECT, related_name='recreadores', to='API.generos')),
                ('nivel', models.ForeignKey(db_column='nivel_id', on_delete=django.db.models.deletion.PROTECT, related_name='recreadores', to='API.nivel')),
                ('persona', models.OneToOneField(db_column='persona_id', on_delete=django.db.models.deletion.PROTECT, related_name='recreador', to='API.personas')),
            ],
            options={
                'db_table': 'recreadores',
            },
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('precio', models.FloatField(default=0)),
                ('duracion', models.DurationField()),
                ('numero_recreadores', models.IntegerField(default=1)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'servicios',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tipo_documentos',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=20, unique=True)),
                ('contraseña', models.CharField(max_length=200)),
                ('inhabilitado', models.BooleanField(default=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cargo', models.ForeignKey(db_column='cargo_id', on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='API.cargos')),
                ('persona', models.OneToOneField(db_column='persona_id', on_delete=django.db.models.deletion.PROTECT, related_name='usuario', to='API.personas')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='ServiciosRecreadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recreador', models.ForeignKey(db_column='recreador_id', on_delete=django.db.models.deletion.CASCADE, related_name='servicio', to='API.recreadores')),
                ('servicio', models.ForeignKey(db_column='servicio_id', on_delete=django.db.models.deletion.CASCADE, related_name='recreador', to='API.servicios')),
            ],
            options={
                'db_table': 'servicios_has_recreadores',
            },
        ),
        migrations.CreateModel(
            name='ServiciosMateriales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.ImageField(default=1, upload_to='')),
                ('material', models.ForeignKey(db_column='material_id', on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='API.materiales')),
                ('servicio', models.ForeignKey(db_column='servicio_id', on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='API.servicios')),
            ],
            options={
                'db_table': 'servicios_has_materiales',
            },
        ),
        migrations.CreateModel(
            name='ServiciosActividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.ForeignKey(db_column='actividad_id', on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='API.actividades')),
                ('servicio', models.ForeignKey(db_column='servicio_id', on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='API.servicios')),
            ],
            options={
                'db_table': 'servicios_has_actividades',
            },
        ),
        migrations.AddField(
            model_name='personas',
            name='tipo_documento',
            field=models.ForeignKey(db_column='tipo_documento_id', on_delete=django.db.models.deletion.PROTECT, related_name='personas', to='API.tipodocumento'),
        ),
        migrations.CreateModel(
            name='PermisosCargos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargos', models.ForeignKey(db_column='cargo_id', on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='API.cargos')),
                ('permisos', models.ForeignKey(db_column='permiso_id', on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='API.permisos')),
            ],
            options={
                'db_table': 'permisos_has_cargos',
            },
        ),
        migrations.CreateModel(
            name='MaterialesActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.ForeignKey(db_column='actividad_id', on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='API.actividades')),
                ('material', models.ForeignKey(db_column='material_id', on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='API.materiales')),
            ],
            options={
                'db_table': 'materiales_has_actividades',
            },
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evento', models.DateTimeField()),
                ('direccion', models.CharField(max_length=500)),
                ('numero_personas', models.IntegerField()),
                ('completado', models.BooleanField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('PrecioDolar', models.ForeignKey(db_column='precio_dolar_id', on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='API.preciodolar')),
                ('cliente', models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='API.clientes')),
            ],
            options={
                'db_table': 'eventos',
            },
        ),
        migrations.AddField(
            model_name='clientes',
            name='persona',
            field=models.ForeignKey(db_column='persona_id', on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='API.personas'),
        ),
    ]
