# Generated by Django 3.2.23 on 2024-08-28 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(max_length=300)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'actividades',
            },
        ),
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(max_length=300)),
                ('administrador', models.BooleanField()),
                ('img', models.FileField(blank=True, null=True, upload_to='img_logo_cargos')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cargos',
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evento_inicio', models.DateTimeField()),
                ('fecha_evento_final', models.DateTimeField()),
                ('direccion', models.CharField(max_length=500)),
                ('numero_personas', models.IntegerField()),
                ('estado', models.BooleanField(default=None, null=True)),
                ('pago_total', models.BooleanField(default=False)),
                ('anticipo', models.BooleanField(default=False)),
                ('opinion', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='API.clientes')),
            ],
            options={
                'db_table': 'eventos',
            },
        ),
        migrations.CreateModel(
            name='Generos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(max_length=300)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'generos',
            },
        ),
        migrations.CreateModel(
            name='Materiales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(max_length=300)),
                ('total', models.IntegerField(default=0)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'materiales',
            },
        ),
        migrations.CreateModel(
            name='MetodosPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(max_length=300)),
                ('referencia', models.BooleanField(default=False)),
                ('capture', models.BooleanField(default=False)),
                ('divisa', models.BooleanField(default=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'metodos_pago',
            },
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(max_length=300)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'niveles',
            },
        ),
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'permisos',
            },
        ),
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('numero_documento', models.BigIntegerField()),
                ('telefono_principal', models.BigIntegerField(unique=True)),
                ('telefono_secundario', models.BigIntegerField(blank=True, default=None, null=True)),
                ('correo', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'personas',
            },
        ),
        migrations.CreateModel(
            name='PrecioDolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.FloatField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'precio_dolar',
            },
        ),
        migrations.CreateModel(
            name='PreguntasEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=100, unique=True)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'preguntas_eventos',
            },
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('precio', models.FloatField(default=0)),
                ('duracion', models.DurationField()),
                ('numero_recreadores', models.IntegerField(default=1)),
                ('descripcion', models.CharField(max_length=500)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'servicios',
            },
        ),
        migrations.CreateModel(
            name='Sobrecargos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(max_length=300)),
                ('monto', models.FloatField(default=0)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sobrecargos',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(max_length=300)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tipos_documentos',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=20, unique=True)),
                ('contraseña', models.CharField(max_length=200)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cargo', models.ForeignKey(db_column='cargo_id', on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='API.cargos')),
                ('persona', models.OneToOneField(db_column='persona_id', on_delete=django.db.models.deletion.PROTECT, related_name='usuario', to='API.personas')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='ServiciosMateriales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('material', models.ForeignKey(db_column='material_id', on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='API.materiales')),
                ('servicio', models.ForeignKey(db_column='servicio_id', on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='API.servicios')),
            ],
            options={
                'db_table': 'servicios_materiales',
            },
        ),
        migrations.CreateModel(
            name='ServiciosActividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.ForeignKey(db_column='actividad_id', on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='API.actividades')),
                ('servicio', models.ForeignKey(db_column='servicio_id', on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='API.servicios')),
            ],
            options={
                'db_table': 'servicios_actividades',
            },
        ),
        migrations.CreateModel(
            name='RegistroMateriales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=300)),
                ('cantidad', models.IntegerField()),
                ('total', models.IntegerField()),
                ('tipo', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(db_column='material_id', on_delete=django.db.models.deletion.CASCADE, related_name='registro', to='API.materiales')),
            ],
        ),
        migrations.CreateModel(
            name='Recreadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('img', models.FileField(blank=True, db_column='img_perfil', null=True, upload_to='img_recreadores')),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('genero', models.ForeignKey(db_column='genero_id', on_delete=django.db.models.deletion.PROTECT, related_name='recreadores', to='API.generos')),
                ('nivel', models.ForeignKey(db_column='nivel_id', on_delete=django.db.models.deletion.PROTECT, related_name='recreadores', to='API.nivel')),
                ('persona', models.OneToOneField(db_column='persona_id', on_delete=django.db.models.deletion.PROTECT, related_name='recreador', to='API.personas')),
            ],
            options={
                'db_table': 'recreadores',
            },
        ),
        migrations.CreateModel(
            name='Privilegios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargos', models.ForeignKey(db_column='cargo_id', on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='API.cargos')),
                ('permisos', models.ForeignKey(db_column='permiso_id', on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='API.permisos')),
            ],
            options={
                'db_table': 'privilegios',
            },
        ),
        migrations.AddField(
            model_name='personas',
            name='tipo_documento',
            field=models.ForeignKey(db_column='tipo_documento_id', on_delete=django.db.models.deletion.PROTECT, related_name='personas', to='API.tipodocumento'),
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.BooleanField(default=False)),
                ('monto', models.FloatField()),
                ('referencia', models.BigIntegerField(blank=True, default=None, null=True)),
                ('capture', models.FileField(blank=True, null=True, upload_to='capture_pago')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(db_column='evento_id', on_delete=django.db.models.deletion.PROTECT, related_name='pago', to='API.eventos')),
                ('metodoPago', models.ForeignKey(db_column='metodo_pago_id', on_delete=django.db.models.deletion.PROTECT, related_name='evento', to='API.metodospago')),
                ('precioDolar', models.ForeignKey(db_column='precio_dolar_id', on_delete=django.db.models.deletion.PROTECT, related_name='pago', to='API.preciodolar')),
            ],
            options={
                'db_table': 'pagos',
            },
        ),
        migrations.CreateModel(
            name='MaterialesActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.ForeignKey(db_column='actividad_id', on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='API.actividades')),
                ('material', models.ForeignKey(db_column='material_id', on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='API.materiales')),
            ],
            options={
                'db_table': 'materiales_actividades',
            },
        ),
        migrations.CreateModel(
            name='EventosSobrecargos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.ForeignKey(db_column='evento_id', on_delete=django.db.models.deletion.CASCADE, related_name='sobrecargo', to='API.eventos')),
                ('sobrecargo', models.ForeignKey(db_column='sobrecargo_id', on_delete=django.db.models.deletion.CASCADE, related_name='evento', to='API.sobrecargos')),
            ],
            options={
                'db_table': 'sobrecargos_eventos',
            },
        ),
        migrations.CreateModel(
            name='EventosServicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluacion_servicio', models.IntegerField(blank=True, null=True)),
                ('evento', models.ForeignKey(db_column='evento_id', on_delete=django.db.models.deletion.CASCADE, related_name='servicio', to='API.eventos')),
                ('servicio', models.ForeignKey(db_column='servicio_id', on_delete=django.db.models.deletion.CASCADE, related_name='evento', to='API.servicios')),
            ],
            options={
                'db_table': 'servicios_eventos',
            },
        ),
        migrations.CreateModel(
            name='EventosRecreadoresServicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluacion_recreador', models.IntegerField(blank=True, null=True)),
                ('evento', models.ForeignKey(db_column='evento_id', on_delete=django.db.models.deletion.CASCADE, related_name='recreador', to='API.eventos')),
                ('recreador', models.ForeignKey(db_column='recreador_id', on_delete=django.db.models.deletion.CASCADE, related_name='evento', to='API.recreadores')),
                ('servicio', models.ForeignKey(db_column='servicio_id', on_delete=django.db.models.deletion.CASCADE, related_name='recreador', to='API.servicios')),
            ],
            options={
                'db_table': 'recreadores_eventos_servicios',
            },
        ),
        migrations.CreateModel(
            name='EventoPreguntasEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('evento', models.ForeignKey(db_column='evento_id', on_delete=django.db.models.deletion.CASCADE, related_name='pregunta', to='API.eventos')),
                ('pregunta', models.ForeignKey(db_column='pregunta_id', on_delete=django.db.models.deletion.CASCADE, related_name='recreador', to='API.preguntasevento')),
            ],
            options={
                'db_table': 'eventos_preguntas_evento',
            },
        ),
        migrations.AddField(
            model_name='clientes',
            name='persona',
            field=models.ForeignKey(db_column='persona_id', on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='API.personas'),
        ),
    ]
