# Generated by Django 3.2.23 on 2024-01-29 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('administrador', models.BooleanField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cargos',
            },
        ),
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'permisos',
            },
        ),
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('numero_documento', models.BigIntegerField(unique=True)),
                ('telefono_principal', models.BigIntegerField()),
                ('telefono_secundario', models.BigIntegerField()),
                ('correo', models.EmailField(blank=True, max_length=100, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'personas',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tipo_documento',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=20, unique=True)),
                ('contraseña', models.CharField(max_length=200)),
                ('inhabilitado', models.BooleanField(default=False)),
                ('cargo', models.ForeignKey(db_column='cargo_id', on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='API.cargos')),
                ('persona', models.OneToOneField(db_column='persona_id', on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='API.personas')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.AddField(
            model_name='personas',
            name='tipo_documento',
            field=models.ForeignKey(db_column='tipo_documento_id', on_delete=django.db.models.deletion.CASCADE, related_name='personas', to='API.tipodocumento'),
        ),
        migrations.CreateModel(
            name='PermisosCargos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargos', models.ForeignKey(db_column='cargos_id', on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='API.cargos')),
                ('permisos', models.ForeignKey(db_column='permisos_id', on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='API.permisos')),
            ],
            options={
                'db_table': 'persmisos_has_cargos',
            },
        ),
    ]
