# Generated by Django 3.2.23 on 2024-08-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventos',
            name='completado',
        ),
        migrations.AddField(
            model_name='eventos',
            name='estado',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
