# Generated by Django 3.2.23 on 2024-01-29 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permisos',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='permisos',
            name='fecha_registro',
        ),
    ]
