# Generated by Django 3.2.23 on 2024-08-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventos',
            name='anticipo',
        ),
        migrations.RemoveField(
            model_name='eventos',
            name='pago_total',
        ),
        migrations.AddField(
            model_name='eventos',
            name='estado_pago',
            field=models.IntegerField(default=0, max_length=1),
        ),
    ]
