# Generated by Django 3.2.23 on 2024-06-19 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20240619_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sobrecargos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('monto', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'sobrecargos',
            },
        ),
        migrations.CreateModel(
            name='EventosSobrecargos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.ForeignKey(db_column='evento_id', on_delete=django.db.models.deletion.CASCADE, related_name='sobrecargo', to='API.eventos')),
                ('sobrecargo', models.ForeignKey(db_column='sobrecargo_id', on_delete=django.db.models.deletion.CASCADE, related_name='evento', to='API.sobrecargos')),
            ],
            options={
                'db_table': 'sobrecargo_has_eventos',
            },
        ),
    ]
