# Generated by Django 3.2.23 on 2024-01-29 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20240129_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permisoscargos',
            name='cargos',
            field=models.ForeignKey(db_column='cargo_id', on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='API.cargos'),
        ),
        migrations.AlterField(
            model_name='permisoscargos',
            name='permisos',
            field=models.ForeignKey(db_column='permiso_id', on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='API.permisos'),
        ),
        migrations.AlterModelTable(
            name='permisoscargos',
            table='permisos_has_cargos',
        ),
    ]
