# Generated by Django 3.2.23 on 2024-08-26 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20240826_0644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recreadores',
            name='inhabilitado',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='inhabilitado',
        ),
        migrations.AddField(
            model_name='recreadores',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
