# Generated by Django 3.2.23 on 2024-08-31 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20240829_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='estado_pago',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='tipo',
            field=models.IntegerField(default=0),
        ),
    ]
