# Generated by Django 3.2.23 on 2024-01-30 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20240129_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='tipo_documento',
            field=models.ForeignKey(db_column='tipo_documento_id', on_delete=django.db.models.deletion.PROTECT, related_name='personas', to='API.tipodocumento'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='cargo',
            field=models.ForeignKey(db_column='cargo_id', on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='API.cargos'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='persona',
            field=models.OneToOneField(db_column='persona_id', on_delete=django.db.models.deletion.PROTECT, related_name='usuario', to='API.personas'),
        ),
    ]
