# Generated by Django 3.2.23 on 2024-09-03 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20240831_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='evaluado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventos',
            name='recreadoresAsignados',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eventopreguntasevento',
            name='evento',
            field=models.ForeignKey(db_column='evento_id', on_delete=django.db.models.deletion.PROTECT, related_name='pregunta', to='API.eventos'),
        ),
        migrations.AlterField(
            model_name='eventopreguntasevento',
            name='pregunta',
            field=models.ForeignKey(db_column='pregunta_id', on_delete=django.db.models.deletion.PROTECT, related_name='recreador', to='API.preguntasevento'),
        ),
        migrations.AlterField(
            model_name='eventosrecreadoresservicios',
            name='evento',
            field=models.ForeignKey(db_column='evento_id', on_delete=django.db.models.deletion.PROTECT, related_name='recreador', to='API.eventos'),
        ),
        migrations.AlterField(
            model_name='eventosrecreadoresservicios',
            name='recreador',
            field=models.ForeignKey(db_column='recreador_id', on_delete=django.db.models.deletion.PROTECT, related_name='evento', to='API.recreadores'),
        ),
        migrations.AlterField(
            model_name='eventosrecreadoresservicios',
            name='servicio',
            field=models.ForeignKey(db_column='servicio_id', on_delete=django.db.models.deletion.PROTECT, related_name='recreador', to='API.servicios'),
        ),
    ]
