# Generated by Django 3.2.23 on 2024-07-01 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_auto_20240630_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventos',
            old_name='PrecioDolar',
            new_name='precioDolar',
        ),
        migrations.RemoveField(
            model_name='eventosservicios',
            name='servicios',
        ),
        migrations.AddField(
            model_name='eventosservicios',
            name='servicio',
            field=models.ForeignKey(db_column='servicio_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='evento', to='API.servicios'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actividades',
            name='descripcion',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='cargos',
            name='descripcion',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='generos',
            name='descripcion',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='materiales',
            name='descripcion',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='nivel',
            name='descripcion',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='permisos',
            name='descripcion',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='descripcion',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='sobrecargos',
            name='descripcion',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='descripcion',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterModelTable(
            name='eventossobrecargos',
            table='sobrecargos_eventos',
        ),
    ]
