# Generated by Django 3.2.23 on 2024-02-07 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_auto_20240129_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='correo',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='personas',
            name='telefono_principal',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterModelTable(
            name='tipodocumento',
            table='tipo_documentos',
        ),
    ]
