# Generated by Django 3.2.23 on 2024-09-04 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_auto_20240903_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='motivo_cancelacion',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
