# Generated by Django 3.2.23 on 2024-09-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_eventos_motivo_cancelacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventos',
            old_name='recreadoresAsignados',
            new_name='recreadores_asignados',
        ),
        migrations.RemoveField(
            model_name='eventosservicios',
            name='evaluacion_servicio',
        ),
        migrations.AlterField(
            model_name='eventopreguntasevento',
            name='respuesta',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='opinion',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
