# Generated by Django 3.2.23 on 2024-07-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_auto_20240701_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodosPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(max_length=300)),
                ('referencia', models.BooleanField(default=False)),
                ('capture', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'metodos_pago',
            },
        ),
        migrations.AlterField(
            model_name='personas',
            name='numero_documento',
            field=models.BigIntegerField(),
        ),
    ]
