# Generated by Django 3.2.23 on 2024-02-08 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_actividades_materiales_nivel_recreadores'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='nivel',
            table='niveles',
        ),
    ]
