# Generated by Django 3.2.23 on 2024-02-15 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_alter_nivel_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('precio', models.FloatField(default=0)),
                ('duracion', models.DurationField()),
                ('numero_recreadores', models.ImageField(default=1, upload_to='')),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'servicios',
            },
        ),
        migrations.CreateModel(
            name='ServiciosRecreadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recreador', models.ForeignKey(db_column='recreador_id', on_delete=django.db.models.deletion.CASCADE, related_name='servicio', to='API.recreadores')),
                ('servicio', models.ForeignKey(db_column='servicio_id', on_delete=django.db.models.deletion.CASCADE, related_name='recreador', to='API.servicios')),
            ],
            options={
                'db_table': 'servicios_has_recreadores',
            },
        ),
        migrations.CreateModel(
            name='Serviciosmateriales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.ImageField(default=1, upload_to='')),
                ('material', models.ForeignKey(db_column='material_id', on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='API.materiales')),
                ('servicio', models.ForeignKey(db_column='servicio_id', on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='API.servicios')),
            ],
            options={
                'db_table': 'servicios_has_materiales',
            },
        ),
        migrations.CreateModel(
            name='ServiciosActividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.ForeignKey(db_column='actividad_id', on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='API.actividades')),
                ('servicio', models.ForeignKey(db_column='servicio_id', on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='API.servicios')),
            ],
            options={
                'db_table': 'servicios_has_actvidades',
            },
        ),
        migrations.CreateModel(
            name='MaterialesActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.ForeignKey(db_column='actividad_id', on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='API.actividades')),
                ('material', models.ForeignKey(db_column='material_id', on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='API.materiales')),
            ],
            options={
                'db_table': 'materiales_has_actvidades',
            },
        ),
    ]
