# Generated by Django 3.2.23 on 2024-07-17 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_auto_20240717_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventos',
            name='precioDolar',
        ),
        migrations.AddField(
            model_name='pagos',
            name='precioDolar',
            field=models.ForeignKey(db_column='precio_dolar_id', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='pago', to='API.preciodolar'),
        ),
        migrations.AddField(
            model_name='pagos',
            name='tipo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='evento',
            field=models.ForeignKey(db_column='evento_id', on_delete=django.db.models.deletion.PROTECT, related_name='pago', to='API.eventos'),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='metodoPago',
            field=models.ForeignKey(db_column='metodo_pago_id', on_delete=django.db.models.deletion.PROTECT, related_name='evento', to='API.metodospago'),
        ),
    ]
