# Generated by Django 3.2.23 on 2024-02-23 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_materialesactividad_servicios_serviciosactividades_serviciosmateriales_serviciosrecreadores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='numero_recreadores',
            field=models.IntegerField(default=1),
        ),
    ]
