# Generated by Django 3.2.23 on 2024-03-13 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_alter_servicios_numero_recreadores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(default='2024-02-11 03:15:20.424000')),
                ('fecha_actualizacion', models.DateTimeField(default='2024-02-11 03:15:20.424000')),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='PrecioDolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.FloatField()),
                ('fecha_registro', models.DateTimeField(default='2024-02-11 03:15:20.424000')),
            ],
            options={
                'db_table': 'precio_dolar',
            },
        ),
        migrations.AddField(
            model_name='actividades',
            name='fecha_actualizacion',
            field=models.DateTimeField(default='2024-02-11 03:15:20.424000'),
        ),
        migrations.AddField(
            model_name='actividades',
            name='fecha_registro',
            field=models.DateTimeField(default='2024-02-11 03:15:20.424000'),
        ),
        migrations.AddField(
            model_name='materiales',
            name='fecha_actualizacion',
            field=models.DateTimeField(default='2024-02-11 03:15:20.424000'),
        ),
        migrations.AddField(
            model_name='materiales',
            name='fecha_registro',
            field=models.DateTimeField(default='2024-02-11 03:15:20.424000'),
        ),
        migrations.AddField(
            model_name='nivel',
            name='fecha_actualizacion',
            field=models.DateTimeField(default='2024-02-11 03:15:20.424000'),
        ),
        migrations.AddField(
            model_name='nivel',
            name='fecha_registro',
            field=models.DateTimeField(default='2024-02-11 03:15:20.424000'),
        ),
        migrations.AddField(
            model_name='servicios',
            name='fecha_actualizacion',
            field=models.DateTimeField(default='2024-02-11 03:15:20.424000'),
        ),
        migrations.AddField(
            model_name='servicios',
            name='fecha_registro',
            field=models.DateTimeField(default='2024-02-11 03:15:20.424000'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='fecha_actualizacion',
            field=models.DateTimeField(default='2024-02-11 03:15:20.424000'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='fecha_registro',
            field=models.DateTimeField(default='2024-02-11 03:15:20.424000'),
        ),
        migrations.AlterField(
            model_name='cargos',
            name='fecha_actualizacion',
            field=models.DateTimeField(default='2024-02-11 03:15:20.424000'),
        ),
        migrations.AlterField(
            model_name='cargos',
            name='fecha_registro',
            field=models.DateTimeField(default='2024-02-11 03:15:20.424000'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='fecha_actualizacion',
            field=models.DateTimeField(default='2024-02-11 03:15:20.424000'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='fecha_registro',
            field=models.DateTimeField(default='2024-02-11 03:15:20.424000'),
        ),
        migrations.AlterField(
            model_name='recreadores',
            name='fecha_actualizacion',
            field=models.DateTimeField(default='2024-02-11 03:15:20.424000'),
        ),
        migrations.AlterField(
            model_name='recreadores',
            name='fecha_registro',
            field=models.DateTimeField(default='2024-02-11 03:15:20.424000'),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='fecha_actualizacion',
            field=models.DateTimeField(default='2024-02-11 03:15:20.424000'),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='fecha_registro',
            field=models.DateTimeField(default='2024-02-11 03:15:20.424000'),
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evento', models.DateTimeField()),
                ('direccion', models.CharField(max_length=500)),
                ('numero_personas', models.IntegerField()),
                ('completado', models.BooleanField()),
                ('fecha_registro', models.DateTimeField(default='2024-02-11 03:15:20.424000')),
                ('fecha_actualizacion', models.DateTimeField(default='2024-02-11 03:15:20.424000')),
                ('PrecioDolar', models.ForeignKey(db_column='precio_dolar_id', on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='API.preciodolar')),
                ('cliente', models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='API.clientes')),
            ],
            options={
                'db_table': 'eventos',
            },
        ),
        migrations.AddField(
            model_name='clientes',
            name='persona',
            field=models.ForeignKey(db_column='persona_id', on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='API.personas'),
        ),
    ]
