# Generated by Django 3.2.23 on 2024-07-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_auto_20240717_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagos',
            name='divisa',
            field=models.BigIntegerField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='referencia',
            field=models.BigIntegerField(blank=True, default=False, null=True),
        ),
    ]
