# Generated by Django 3.2.23 on 2024-08-04 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0012_eventosrecreadore'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventosrecreadore',
            name='servicio',
            field=models.ForeignKey(db_column='servicio_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recreador', to='API.servicios'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='eventosrecreadore',
            table='recreadores_eventos_servicio',
        ),
    ]
