# Generated by Django 3.2.23 on 2024-06-05 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0012_auto_20240602_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='recreadores',
            name='genero',
            field=models.ForeignKey(db_column='genero_id', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='recreadores', to='API.generos'),
        ),
    ]
