# Generated by Django 3.2.23 on 2024-08-04 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0013_auto_20240804_1409'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventosRecreadore',
            new_name='EventosRecreadoresServicios',
        ),
        migrations.AlterModelTable(
            name='eventosrecreadoresservicios',
            table='recreadores_eventos_servicios',
        ),
    ]
