# Generated by Django 3.2.23 on 2024-08-15 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0015_auto_20240810_2109'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tipodocumento',
            table='tipos_documentos',
        ),
    ]
