
MESSAGE={
    "registerActividad":"Registro de actividad completado",
    "registerCargo":"Registro de cargo completado",
    "registerGenero":"Registro de genero completado",
    "registerMaterial":"Registro de material completado",
    "registerNivel":"Registro de nivel completado",
    "registerTipoDocumento":"Registro de tipo de documento completado",
    "registerSobrecargo":"Registro de sobrecargo completado",
    "registerServicio":"Registro de servicio completado",
    "registerRecreador":"Registro de recreador completado",
    "exitoGet":"Exito",
    "edition":"Exito. Registro editado",
    "delete":"Exito. Registro eliminado",
    "Acceso":"Acceso permitido", 
    
    "errorRegistro":"Error al registrar",
    "errorEdition":"Error al editar",
    "errorEliminar":"Error al eliminar",
    "errorConsulta":"Error al consultar",
    "errorProtect":"Error. Registro protejido no se puede eliminar",
    "errorRegistroNone":"Error. Registro no encontrado",
    "errorRegistrosNone":"Error. No se encontraron registros en el sistema",
    "errorPost":"Error consulta post",
    "errorGet":"Error consulta get",
    "errorPut":"Error de consulta put",
    "errorIntegrity":"Error de integridad",
    "errorDuplicate":"Error de campo duplicado",
    "errorDelete":"Error de consulta put",
    "errorProteccion":"Error de protección",
    "userPassword": "Usuario o contraseña incorrecta por favor verifique",
    "errorSystem":'Error en el sistema. Intente mas tarde', 

    "errorGenero":"Error. Compruebe el genero",
    "errorNivel":"Error. Compruebe el nivel",
    "errorTipoDocumento":"Error. Compruebe el tipo de documento",
    "errorCargo":"Error. Compruebe el cargo",
    

    "nombreDuplicate": "Nombre duplicado. El campo nombre debe ser unico",
    "correoDuplicate": "Correo duplicado. El campo correo debe ser unico",
    "documentoDuplicate": "Número de Documento duplicado. El campo numero de documento debe ser unico",
    "telefonoPrincipalDuplicate": "Teléfono duplicado. El campo teléfono principal debe ser unico",
}