
MESSAGE={
    'registerActividad':'Registro de actividad completado',
    'registerCargo':'Registro de cargo completado',
    'registerMetodoPago':'Registro de metodo de pago completado',
    'registerGenero':'Registro de genero completado',
    'registerMaterial':'Registro de material completado',
    'registerNivel':'Registro de nivel completado',
    'registerTipoDocumento':'Registro de tipo de documento completado',
    'registerSobrecargo':'Registro de sobrecargo completado',
    'registerServicio':'Registro de servicio completado',
    'registerRecreador':'Registro de recreador completado',
    'registerRecreadores':'Asignación de recreadores completado',
    'registerEvaluacion':'Evaluacion Registrada',
    'registerEvento':'Registro de evento completado',
    'registerPago':'Registro de pago completado',
    'registerPregunta':'Registro de pregunta completado',
    'registerUsuario':'Registro de usuario completado',
    'respaldoExit':'Respaldo Completado',
    'exitoGet':'Exito',
    'exitoUserDisabled':'Exito. Usuario Desativado',
    'edition':'Exito. Registro editado',
    'editRecreadores':'Asignación de recreadores completado',
    'delete':'Exito. Registro eliminado',
    'eventoCancelado':'Evento Cancelado',
    'eventoCompletado':'Evento Completado',
    'Acceso':'Acceso permitido', 
    
    'errorRegistro':'Error al registrar',
    'errorEdition':'Error al editar',
    'errorEliminar':'Error al eliminar',
    'errorEventoFecha':'Error Evento Pasado',
    'errorConsulta':'Error al consultar',
    'errorProtect':'Error. Registro protejido no se puede eliminar',
    'errorRegistroNone':'Error. Registro no encontrado',
    'errorRegistrosNone':'Error. No se encontraron registros en el sistema',
    'errorPost':'Error consulta post',
    'errorGet':'Error consulta get',
    'errorPut':'Error de consulta put',
    'errorIntegrity':'Error de integridad',
    'errorDuplicate':'Error de campo duplicado',
    'errorPago':'No existen ningun pago a registrar',
    'errorDelete':'Error de consulta put',
    'errorEstado':'Error de Estado',
    'errorEventoEvaluado':'Error. Evento Evaluado',
    'errorProteccion':'Error de protección',
    'errorProtectEvento':'Evento protejido, no se puede eliminar',
    'errorPagado':'Evento pagado, no se puede eliminar',
    'userPassword': 'Usuario o contraseña incorrecta por favor verifique',
    'errorSystem':'Error en el sistema. Intente mas tarde', 
    'errorRegistrosPermisos': 'Permisos no encontrados',
    'errorRegistrosPersonas': 'Personas no encontrados',
    'errorDollar': 'Error al buscar precio BCV actualizado',
    'errorRespaldo':"Error Respaldo Incompleto",
    'errorProcces':"Error, Respaldo Interrumpido",

    'errorGenero':'Error. Compruebe el genero',
    'errorContraseña':'Error. Contraseñas diferentes',
    'errorEventoNoCompletado':'Error. Evento no Completado',
    'errorCliente':'Error. Compruebe que existe el cliente seleccionado',
    'errorNivel':'Error. Compruebe el nivel',
    'errorTipoDocumento':'Error. Compruebe el tipo de documento',
    'errorEvento':'Error. Compruebe el evento',
    'errorEventoCompletado':'Error. Evento Completado',
    'errorEventoCancelado':'Error. Evento Cancelado',
    'errorEventoPasado':'Error. Fecha de Evento Transcurrio ',
    'errorPersona':'Error. Compruebe la Persona',
    'errorDuplicateRecreador':'Error. Recreador Duplicado',
    'errorCargo':'Error. Compruebe el cargo',
    'errorRegistroPersona':'Error. Compruebe datos de registro',
    'errorEventoNoTranscurrido':'Error. Fecha de Evento no transcurrido',
    'errorEventoNoPagado':'Error. Evento no Pagado Completamente',
    

    'nombreDuplicate': 'Nombre duplicado. El campo nombre debe ser unico',
    'usuarioDuplicate': 'Usuario duplicado. El campo nombre debe ser unico',
    'preguntaDuplicate': 'Pregunta duplicado.',
    'tipoPago': 'Tipo de Pago no valido',
    'correoDuplicate': 'Correo duplicado. El campo correo debe ser unico',
    'documentoDuplicate': 'Documento duplicado. El campo numero de documento debe ser unico',
    'telefonoPrincipalDuplicate': 'Teléfono duplicado. El campo teléfono principal debe ser unico',
}