
MESSAGE={
    'registerActividad':'Registro de actividad completado',
    'registerCargo':'Registro de cargo completado',
    'registerMetodoPago':'Registro de método de pago completado',
    'registerGenero':'Registro de genero completado',
    'registerMaterial':'Registro de material completado',
    'registerNivel':'Registro de nivel completado',
    'registerTipoDocumento':'Registro de tipo de documento completado',
    'registerSobrecosto':'Registro de sobrecosto completado',
    'registerServicio':'Registro de servicio completado',
    'registerRecreador':'Registro de recreador completado',
    'registerRecreadores':'Asignación de recreadores completado',
    'registerEvaluacion':'Evaluación registrada',
    'registerEvento':'Registro de evento completado',
    'registerPago':'Registro de pago completado',
    'registerPregunta':'Registro de pregunta completado',
    'registerUsuario':'Registro de usuario completado',
    'registerInventario':'Registro de inventario completado',
    'respaldoExit':'Respaldo Completado',
    'exitoGet':'Exito',
    'exitoUserDisabled':'Exito. Usuario desactivado',
    'exitoRecreadorDisabled': 'Éxito. Recreador desactivado',
    'edition':'Exito. Registro editado',
    'editRecreadores':'Asignación de recreadores completado',
    'delete':'Exito. Registro eliminado',
    'eventoCancelado':'Evento cancelado',
    'eventoCompletado':'Evento completado',
    'Acceso':'Acceso permitido', 
    
    'errorRegistro':'Error al registrar',
    'errorEdition':'Error al editar',
    'errorEliminar':'Error al eliminar',
    'errorEventoFecha':'Error. Evento pasado',
    'errorConsulta':'Error al consultar',
    'errorProtect':'Error. Registro protegido no se puede eliminar',
    'errorRegistroNone':'Error. Registro no encontrado',
    'errorRegistrosNone':'Error. No se encontraron registros en el sistema',
    'errorPost':'Error consulta post',
    'errorGet':'Error consulta get',
    'errorPut':'Error de consulta put',
    'errorIntegrity':'Error de integridad',
    'errorCargoAdministrador':'Error. Cargo administrador no se puede eliminar',
    'errorDuplicate':'Error de campo duplicado',
    'errorPago':'No existen ningún pago a registrar',
    'errorDelete':'Error de consulta put',
    'errorEstado':'Error de estado',
    'errorEventoEvaluado':'Error. Evento evaluado',
    'errorProteccion':'Error de protección',
    'errorProtectEvento':'Evento protegido, no se puede eliminar',
    'errorPagado':'Evento pagado, no se puede eliminar',
    'userPassword': 'Usuario o contraseña incorrecta por favor verifique',
    'errorSystem':'Error en el sistema. Intente más tarde', 
    'errorRegistrosPermisos': 'Permisos no encontrados',
    'errorRegistrosPersonas': 'Personas no encontrados',
    'errorDollar': 'Error al buscar precio BCV actualizado',
    'errorRespaldo':'Error Respaldo incompleto',
    'errorProcces':'Error, Respaldo interrumpido',
    'NonePermisos':'No es administrador, ni tiene los permisos necesarios',

    'errorGenero':'Error. Compruebe el género',
    'errorContraseña':'Error. Contraseñas diferentes',
    'errorEventoNoCompletado':'Error. Evento no Completado',
    'errorCliente':'Error. Compruebe que existe el cliente seleccionado',
    'errorNivel':'Error. Compruebe el nivel',
    'errorTipoDocumento':'Error. Compruebe el tipo de documento',
    'errorEvento':'Error. Compruebe el evento',
    'errorMontoSuperior':'Error. Monto superior al debido',
    'errorTipoMaterial':'Error. Tipo de Registro desconocido',
    'inventarioNegativo':'Error. Material en negativo',
    'inventarioNone':'Error. Inventario Insuficiente',
    'errorEventoCompletado':'Error. Evento completado',
    'errorEventoCancelado':'Error. Evento cancelado',
    'errorEventoPasado':'Error. Fecha de evento transcurrió ',
    'errorPersona':'Error. Compruebe la persona',
    'errorDuplicateRecreador':'Error. Recreador duplicado',
    'errorCargo':'Error. Compruebe el cargo',
    'errorCargo':'Error. Compruebe el material',
    'errorRegistroPersona':'Error. Compruebe datos de registro',
    'errorEventoNoTranscurrido':'Error. Fecha de evento no transcurrido',
    'errorEventoNoPagado':'Error. Evento no pagado Completamente',
    'errorDisabledNot':'Este usuario no se puede deshabilitar',
    'errorAdministradorProtegido':'Cargo de administrador protegido',

    'nombreDuplicate': 'Nombre duplicado',
    'usuarioDuplicate': 'Usuario duplicado',
    'preguntaDuplicate': 'Pregunta duplicado.',
    'tipoPago': 'Tipo de Pago no valido',
    'correoDuplicate': 'Correo duplicado',
    'documentoDuplicate': 'Número de documento duplicado',
    'telefonoPrincipalDuplicate': 'Teléfono principal duplicado',
}
