from django.urls import path
from .views.view import Metodos_Pagos_Views, Actividades_Views, Cargos_Views, Clientes_Views, Dollar_View, Eventos_Views, Genero_Views, Login, Materiales_Views, Nivel_Views, Permisos_Views, Persona_Views, Recreadores_Views, Respaldo, Servicios_Views, Sobrecargo_Views, Tipo_Documento_Views, Usuario_Views, Verify_Token_Views, Pagos_Views

urlpatterns=[
    path('cargos/', Cargos_Views.as_view(), name='cargos'),
    path('cargos/<int:id>/', Cargos_Views.as_view(), name='cargo'),
    path('permisos/', Permisos_Views.as_view(), name='permisos'),
    path('tipo_documentos/', Tipo_Documento_Views.as_view(), name='tipo_documentos'),
    path('tipo_documentos/<int:id>/', Tipo_Documento_Views.as_view(), name='tipo_documento'),
    path('niveles/', Nivel_Views.as_view(), name='niveles'),
    path('dolar/', Dollar_View.as_view(), name='doalr'),
    path('niveles/<int:id>/', Nivel_Views.as_view(), name='nivel'),
    path('generos/', Genero_Views.as_view(), name='generos'),
    path('generos/<int:id>/', Genero_Views.as_view(), name='genero'),
    path('sobrecargos/', Sobrecargo_Views.as_view(), name='sobrecargos'),
    path('sobrecargos/<int:id>/', Sobrecargo_Views.as_view(), name='sobrecargo'),
    path('actividades/', Actividades_Views.as_view(), name='actividades'),
    path('actividades/<int:id>/', Actividades_Views.as_view(), name='actividad'),
    path('materiales/', Materiales_Views.as_view(), name='materiales'),
    path('materiales/<int:id>/', Materiales_Views.as_view(), name='material'),
    path('metodos_pago/', Metodos_Pagos_Views.as_view(), name='metodos_pago'),
    path('metodos_pago/<int:id>/', Metodos_Pagos_Views.as_view(), name='metodo_pago'),
    path('servicios/', Servicios_Views.as_view(), name='servicios'),
    path('servicios/<int:id>/', Servicios_Views.as_view(), name='servicio'),
    path('personas/<int:tipo_documento>/<int:documento>/', Persona_Views.as_view(), name='personas'),
    path('usuarios/', Usuario_Views.as_view(), name='usuarios'),
    path('recreadores/', Recreadores_Views.as_view(), name='recreadores'),
    path('recreadores/<str:identificador>/', Recreadores_Views.as_view(), name='recreadores'),
    path('eventos/', Eventos_Views.as_view(), name='eventos'),
    path('eventos/<int:id>/', Eventos_Views.as_view(), name='evento'),
    path('clientes/', Clientes_Views.as_view(), name='clientes'),
    path('clientes/<str:identificador>/', Clientes_Views.as_view(), name='cliente'),
    path('login/', Login.as_view(), name='login'),
    path('verify/', Verify_Token_Views.as_view(), name='verify'),
    path('pagos/', Pagos_Views.as_view(), name='pagos'),
    path('respaldo/', Respaldo.as_view(), name='resldo'),
]